# Generated by Django 5.0.3 on 2024-04-21 22:24

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_curso_imagen_estudiante_avatar_instructor_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='contenido',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
