# Generated by Django 5.0.3 on 2024-04-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_curso_contenido_alter_curso_descripcion'),
        ('cursos', '0011_curso_contenido_alter_curso_descripcion'),
    ]

    operations = [
    ]
